/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./../../../src/components/ui/badge/Badge.vue')['default']
    BentoIcon: typeof import('./../../../src/components/icons/BentoIcon.vue')['default']
    Button: typeof import('./../../../src/components/ui/button/Button.vue')['default']
    Card: typeof import('./../../../src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./../../../src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./../../../src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./../../../src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./../../../src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./../../../src/components/ui/card/CardTitle.vue')['default']
    Code: typeof import('./../../../src/components/layout/Code.vue')['default']
    CodePreview: typeof import('./../../../src/components/layout/CodePreview.vue')['default']
    Installation: typeof import('./../../../src/components/layout/Installation.vue')['default']
    Menubar: typeof import('./../../../src/components/ui/menubar/Menubar.vue')['default']
    MenubarCheckboxItem: typeof import('./../../../src/components/ui/menubar/MenubarCheckboxItem.vue')['default']
    MenubarContent: typeof import('./../../../src/components/ui/menubar/MenubarContent.vue')['default']
    MenubarGroup: typeof import('./../../../src/components/ui/menubar/MenubarGroup.vue')['default']
    MenubarItem: typeof import('./../../../src/components/ui/menubar/MenubarItem.vue')['default']
    MenubarLabel: typeof import('./../../../src/components/ui/menubar/MenubarLabel.vue')['default']
    MenubarMenu: typeof import('./../../../src/components/ui/menubar/MenubarMenu.vue')['default']
    MenubarRadioGroup: typeof import('./../../../src/components/ui/menubar/MenubarRadioGroup.vue')['default']
    MenubarRadioItem: typeof import('./../../../src/components/ui/menubar/MenubarRadioItem.vue')['default']
    MenubarSeparator: typeof import('./../../../src/components/ui/menubar/MenubarSeparator.vue')['default']
    MenubarShortcut: typeof import('./../../../src/components/ui/menubar/MenubarShortcut.vue')['default']
    MenubarSub: typeof import('./../../../src/components/ui/menubar/MenubarSub.vue')['default']
    MenubarSubContent: typeof import('./../../../src/components/ui/menubar/MenubarSubContent.vue')['default']
    MenubarSubTrigger: typeof import('./../../../src/components/ui/menubar/MenubarSubTrigger.vue')['default']
    MenubarTrigger: typeof import('./../../../src/components/ui/menubar/MenubarTrigger.vue')['default']
    ResizableHandle: typeof import('./../../../src/components/ui/resizable/ResizableHandle.vue')['default']
    ResizablePanelGroup: typeof import('./../../../src/components/ui/resizable/ResizablePanelGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sonner: typeof import('./../../../src/components/ui/sonner/Sonner.vue')['default']
    Table: typeof import('./../../../src/components/ui/table/Table.vue')['default']
    TableBody: typeof import('./../../../src/components/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./../../../src/components/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./../../../src/components/ui/table/TableCell.vue')['default']
    TableEmpty: typeof import('./../../../src/components/ui/table/TableEmpty.vue')['default']
    TableFooter: typeof import('./../../../src/components/ui/table/TableFooter.vue')['default']
    TableHead: typeof import('./../../../src/components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./../../../src/components/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./../../../src/components/ui/table/TableRow.vue')['default']
    Tabs: typeof import('./../../../src/components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./../../../src/components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./../../../src/components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./../../../src/components/ui/tabs/TabsTrigger.vue')['default']
    TheFooter: typeof import('./../../../src/components/layout/TheFooter.vue')['default']
  }
}
